name = str(input("Student name: "))
lab = int(input("Lab grade: "))
midterm = int(input("Midterm grade: "))
final = int(input("Final grade: "))
avarage = float(lab*0.25)+float(midterm*0.35)+float(final*0.40)
print("Name:",name)
print("Lab:",lab)
print("Midterm",midterm)
print("Final",final)
print("Last score:",avarage)